// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUser struct {
	EmailAddress string `json:"emailAddress"`
	Password     string `json:"password"`
}

type User struct {
	ID                   string    `json:"id"`
	EmailAddress         string    `json:"emailAddress"`
	HashedUserID         string    `json:"hashedUserId"`
	PasswordHash         string    `json:"passwordHash"`
	Projects             []string `json:"projects"`
	APIKey               string    `json:"apiKey"`
	TimeZone             string    `json:"timeZone"`
	NotificationTurnedOn bool      `json:"notificationTurnedOn"`
}
